//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetZ.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetZ.Web.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body&gt;
        ///    &lt;h1 id=&quot;divTitulo&quot;&gt;
        ///        Atualização da documentação &lt;a href=&quot;_url_documentacao&quot; target=&quot;_blank&quot;&gt;&quot;_doc_nome&quot;&lt;/a&gt;
        ///    &lt;/h1&gt;
        ///    &lt;h3 id=&quot;divDescricao&quot;&gt;
        ///        _email_descricao
        ///    &lt;/h3&gt;
        ///    &lt;hr /&gt;
        ///    &lt;div id=&quot;divConteudo&quot;&gt;
        ///        &lt;ul&gt;
        ///            _email_conteudo
        ///        &lt;/ul&gt;
        ///    &lt;/div&gt;
        ///    &lt;hr /&gt;
        ///    &lt;div id=&quot;divRodape&quot;&gt;
        ///        Caso você não queira mais receber atualizações para esta documentação basta &lt;a href=&quot;_link_cancelar&quot;&gt;clique aqui&lt;/a&gt;.
        ///    &lt;/div&gt;
        ///&lt;/body&gt;.
        /// </summary>
        internal static string documentacao_email {
            get {
                return ResourceManager.GetString("documentacao_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;
        ///    &lt;a href=&quot;_artigo_link&quot; target=&quot;_blank&quot;&gt;&quot;_artigo_nome&quot;&lt;/a&gt; (_tipo_alteracao).
        ///&lt;/li&gt;.
        /// </summary>
        internal static string documentacao_email_item {
            get {
                return ResourceManager.GetString("documentacao_email_item", resourceCulture);
            }
        }
    }
}
